modLoader="javafml" #mandatory
loaderVersion="[44,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="https://github.com/CreeperHost/SoulShards/blob/1.18/LICENSE.md"
[[mods]] #mandatory
modId="soulshards" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SoulShards" #mandatory
logoFile="logo.png" #optional
credits="" #optional
authors="CreeperHost, tehnut" #optional
description='''

'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.soulshards]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[44.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.soulshards]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soulshards]]
    modId="polylib"
    mandatory=true
    versionRange="[1903,)"
    ordering="NONE"
    side="BOTH"
